In [2]:
import numpy as np
from sklearn import preprocessing
import tensorflow as tf

In [3]:
raw_csv = np.loadtxt("./Downloads/Audiobooks-data.csv", delimiter = ",")

In [4]:
inputs_all = raw_csv[:,1:-1]
targets_all = raw_csv[:,-1]
len(targets_all)

14084

In [5]:
num_of_ones = int(np.sum(targets_all))
print(num_of_ones)
zero_counter = 0
indices_to_be_removed = []

for i in range(len(targets_all)):
    if(targets_all[i] == 0):
    
        zero_counter += 1
        if(zero_counter>num_of_ones):
        
            indices_to_be_removed.append(i)
        

inputs_equal_priors = np.delete(inputs_all, indices_to_be_removed, axis = 0)
targtes_equal_priors = np.delete(targets_all, indices_to_be_removed, axis = 0)
#standardize

scaled_inputs = preprocessing.scale(inputs_equal_priors)

2237


In [6]:
scaled_inputs.shape[0]

4474

In [7]:
shuffled_indices = np.arange(scaled_inputs.shape[0])
np.random.shuffle(shuffled_indices)

shuffled_inputs = scaled_inputs[shuffled_indices]
shuffled_targets = targtes_equal_priors[shuffled_indices]

In [8]:
samples_count = shuffled_inputs.shape[0]
train_samples_count = int(0.8*(samples_count))
validation_samples_count = int(0.1*(samples_count))
test_samples_count = int(0.1*(samples_count))

train_inputs = shuffled_inputs[:train_samples_count]
train_targets = shuffled_targets[:train_samples_count]

validation_inputs = shuffled_inputs[train_samples_count:train_samples_count+validation_samples_count]
validation_targets = shuffled_targets[train_samples_count:train_samples_count+validation_samples_count]

test_inputs = shuffled_inputs[train_samples_count+validation_samples_count:]
test_targets = shuffled_targets[train_samples_count+validation_samples_count:]

In [9]:
np.savez("Audiobook_train", inputs = train_inputs, targets = train_targets)
np.savez("Audiobook_validation", inputs = validation_inputs, targets = validation_targets)
np.savez("Audiobook_test", inputs = test_inputs, targets = test_targets)


In [10]:
inputs_1_all = raw_csv[:,1:-1]
targets_1_all = raw_csv[:,-1]
print(targets_1_all)

[1. 1. 1. ... 0. 0. 0.]


In [11]:
len(targets_1_all)

14084

In [12]:
shuffled_indices = np.arange(inputs_1_all.shape[0])

In [13]:
print(shuffled_indices)

[    0     1     2 ... 14081 14082 14083]


In [14]:
np.random.shuffle(shuffled_indices)

In [15]:
shuffled_inputs_1_all = inputs_1_all[shuffled_indices]
shuffled_targets_1_all = targets_1_all[shuffled_indices]

In [16]:
print(shuffled_targets_1_all)

[0. 0. 0. ... 0. 0. 0.]


In [17]:
zero_counter_1 = 0
num_of_ones_1 = np.sum(shuffled_targets_1_all)
indices_remove = []

for i in range(len(shuffled_targets_1_all)):
    if (shuffled_targets_1_all[i] == 0):
        zero_counter_1 += 1
        if(zero_counter_1 > num_of_ones_1):
            indices_remove.append(i)

balanced_inputs = np.delete(shuffled_inputs_1_all, indices_remove, axis = 0)
balanced_targets = np.delete(shuffled_targets_1_all, indices_remove, axis = 0)
            

In [18]:
scaled_inputs = preprocessing.scale(balanced_inputs)

In [19]:
total_samples_count = len(balanced_targets)

training_count = int(0.8*(total_samples_count))
validation_count = int(0.1*(total_samples_count))
test_count = int(0.1*(total_samples_count))

In [26]:
npz = np.load("Audiobook_train.npz")
train_inputs = npz["inputs"]
train_targets = npz["targets"]

In [21]:
npz = np.load("Audiobook_validation.npz")
vlalidation_inputs = npz["inputs"]
validation_targets = npz["targets"]

In [22]:
npz = np.load("Audiobook_test.npz")
test_inputs = npz["inputs"]
test_targets = npz["targets"]

In [23]:
print(validation_targets)

[1. 0. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 1.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 1. 1.
 0. 1. 1. 0. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0.
 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0.
 0. 0. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 1. 1. 0.
 1. 0. 1. 1. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1.
 1. 1. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1.
 1. 0. 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0.
 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0.
 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 1.
 1. 0. 0. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1.
 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1.
 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1.

In [24]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(50, activation = "relu"),
    tf.keras.layers.Dense(50, activation = "relu"),
    tf.keras.layers.Dense(2, activation = "softmax")
])

model.compile(optimizer = "Adam", loss = "sparse_categorical_crossentropy", metrics = ["accuracy"])

Instructions for updating:
Colocations handled automatically by placer.


In [27]:
early_stopping = tf.keras.callbacks.EarlyStopping()
model.fit(train_inputs, train_targets, batch_size = 100, epochs = 100, callbacks = [early_stopping],
          validation_data = (validation_inputs, validation_targets), verbose = 2)

AttributeError: 'NpzFile' object has no attribute 'shape'

In [106]:
loss, accuracy = model.evaluate(test_inputs, test_targets)

448/448 [==============================] - 0s 61us/sample - loss: 0.2790 - acc: 0.8929
